"""Build the journal-formatted Typst manuscript from the Markdown draft.

The Markdown file remains the content source of truth.  This script performs a
small, deterministic conversion for the syntax used by the paper and writes a
Typst entry file plus a generated body file under ``docs/``.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs" / "paper_draft_20260805.md"
ENTRY = ROOT / "docs" / "paper_journal_20260805.typ"
BODY = ROOT / "docs" / "paper_journal_body_20260805.typ"


def _section(lines: list[str], start: str, end: str) -> list[str]:
    start_idx = lines.index(start) + 1
    end_idx = lines.index(end, start_idx)
    return lines[start_idx:end_idx]


def _paragraph_text(lines: list[str]) -> str:
    """Join hard-wrapped prose without inserting spaces at CJK boundaries."""

    parts = [line.strip() for line in lines if line.strip()]
    if not parts:
        return ""

    result = parts[0]
    cjk_or_punctuation = re.compile(
        r"[\u3400-\u9fff，。；：、！？（）」』】》—–]"
    )
    for part in parts[1:]:
        separator = ""
        if not (
            cjk_or_punctuation.fullmatch(result[-1])
            or cjk_or_punctuation.fullmatch(part[0])
        ):
            separator = " "
        result += separator + part
    return result


def _strip_markdown_emphasis(text: str) -> str:
    return text.replace("**", "").strip()


def _typst_inline(text: str) -> str:
    """Convert the limited inline Markdown used in the manuscript."""

    replacements: list[str] = []

    def stash(value: str) -> str:
        token = f"\ue000{len(replacements)}\ue001"
        replacements.append(value)
        return token

    def code(match: re.Match[str]) -> str:
        value = match.group(1).replace("\\", "\\\\").replace('"', '\\"')
        return stash(f'#raw("{value}")')

    def link(match: re.Match[str]) -> str:
        label = match.group(1)
        url = match.group(2).replace('"', '\\"')
        return stash(f'#link("{url}")[{label}]')

    def autolink(match: re.Match[str]) -> str:
        url = match.group(1).replace('"', '\\"')
        return stash(f'#link("{url}")[{url}]')

    def bold(match: re.Match[str]) -> str:
        return stash(f'*{match.group(1)}*')

    def italic(match: re.Match[str]) -> str:
        return stash(f'_{match.group(1)}_')

    def inline_math(match: re.Match[str]) -> str:
        value = match.group(1)
        value = value.replace(r"\gamma", "gamma")
        value = value.replace(r"\in", " in ")
        value = value.replace(r"\ldots", "dots")
        value = value.replace(r"\{", "lr({").replace(r"\}", "})")
        value = re.sub(r"\^\{([^}]+)\}", r"^(\1)", value)
        return stash(f"${value}$")

    text = re.sub(r"`([^`]+)`", code, text)
    text = re.sub(r"\\\((.+?)\\\)", inline_math, text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", link, text)
    text = re.sub(r"<(https?://[^>]+)>", autolink, text)
    text = re.sub(r"\*\*([^*]+)\*\*", bold, text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", italic, text)
    text = text.replace("@", r"\@").replace("#", r"\#").replace("$", r"\$")

    for idx, value in enumerate(replacements):
        text = text.replace(f"\ue000{idx}\ue001", value)
    return text


def _content(value: str) -> str:
    return f"[{_typst_inline(value.strip())}]"


def _split_table_row(line: str) -> list[str]:
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def _is_separator_row(cells: list[str]) -> bool:
    return all(re.fullmatch(r":?-{3,}:?", cell) for cell in cells)


def _emit_table(caption: str, rows: list[list[str]]) -> str:
    if len(rows) < 2 or not _is_separator_row(rows[1]):
        raise ValueError(f"Malformed Markdown table below {caption!r}")

    header = rows[0]
    data = rows[2:]
    columns = len(header)
    if any(len(row) != columns for row in data):
        raise ValueError(f"Inconsistent column count below {caption!r}")

    header_cells = ", ".join(_content(cell) for cell in header)
    data_cells = ",\n    ".join(
        _content(cell) for row in data for cell in row
    )
    wide = "true" if columns >= 4 else "false"
    return (
        f"#journal-table(\n"
        f"  caption: {_content(caption)},\n"
        f"  columns: {columns},\n"
        f"  header: ({header_cells}),\n"
        f"  cells: (\n    {data_cells},\n  ),\n"
        f"  wide: {wide},\n"
        f")"
    )


def _convert_body(lines: list[str]) -> str:
    output: list[str] = [
        "// Generated by scripts/build_typst_paper.py; edit the Markdown source instead.",
        "#let paper-body(journal-table, journal-figure) = [",
    ]
    paragraph: list[str] = []
    pending_caption: str | None = None
    idx = 0

    def flush_paragraph() -> None:
        if paragraph:
            output.append(_typst_inline(_paragraph_text(paragraph)))
            output.append("")
            paragraph.clear()

    while idx < len(lines):
        line = lines[idx]
        stripped = line.strip()

        if not stripped:
            flush_paragraph()
            idx += 1
            continue

        table_caption = re.fullmatch(r"\*\*(表\s+\d+\s+.+)\*\*", stripped)
        if table_caption:
            flush_paragraph()
            pending_caption = table_caption.group(1)
            idx += 1
            continue

        if stripped.startswith("|"):
            flush_paragraph()
            rows: list[list[str]] = []
            while idx < len(lines) and lines[idx].strip().startswith("|"):
                rows.append(_split_table_row(lines[idx]))
                idx += 1
            if pending_caption is None:
                raise ValueError("Table has no preceding numbered caption")
            output.append(_emit_table(pending_caption, rows))
            output.append("")
            pending_caption = None
            continue

        figure_match = re.fullmatch(r"!\[([^]]+)\]\(([^)]+)\)", stripped)
        if figure_match:
            flush_paragraph()
            caption, path = figure_match.groups()
            wide_captions = ("典型错误", "少标签电池", "专用电池", "零样本插补")
            wide = "true" if any(value in caption for value in wide_captions) else "false"
            output.append(
                f'#journal-figure("{path}", {_content(caption)}, wide: {wide})'
            )
            output.append("")
            idx += 1
            continue

        if stripped == r"\[":
            flush_paragraph()
            while idx < len(lines) and lines[idx].strip() != r"\]":
                idx += 1
            if idx == len(lines):
                raise ValueError("Unterminated display equation")
            output.append(
                '#math.equation(block: true, $ "Macro-F1" = 1/K sum_(k=1)^K '
                '(2 P_k R_k)/(P_k + R_k), quad K = 3 $)'
            )
            output.append("")
            idx += 1
            continue

        heading_match = re.fullmatch(r"(#{2,3})\s+(.+)", stripped)
        if heading_match:
            flush_paragraph()
            level = "=" if len(heading_match.group(1)) == 2 else "=="
            output.append(f"{level} {_typst_inline(heading_match.group(2))}")
            output.append("")
            idx += 1
            continue

        ordered_match = re.match(r"^\d+\.\s+(.+)", stripped)
        bullet_match = re.match(r"^-\s+(.+)", stripped)
        if ordered_match or bullet_match:
            flush_paragraph()
            marker = "+" if ordered_match else "-"
            item = (ordered_match or bullet_match).group(1)
            idx += 1
            continuation: list[str] = []
            while idx < len(lines):
                next_line = lines[idx]
                if next_line.startswith("   ") and next_line.strip():
                    continuation.append(next_line.strip())
                    idx += 1
                else:
                    break
            value = _paragraph_text([item, *continuation])
            output.append(f"{marker} {_typst_inline(value)}")
            continue

        paragraph.append(stripped)
        idx += 1

    flush_paragraph()
    return "\n".join(output).rstrip() + "\n]\n"


ENTRY_TEMPLATE = r'''// Journal-formatted manuscript generated from paper_draft_20260805.md.
// Regenerate with: python3 scripts/build_typst_paper.py

#import "paper_journal_body_20260805.typ": paper-body

#set page(
  paper: "a4",
  margin: (top: 18mm, bottom: 18mm, left: 16mm, right: 16mm),
  header: align(center)[
    #text(size: 7.5pt, fill: luma(95))[充电功率时序故障分类：TCN 与 MOMENT 比较]
  ],
  footer: context align(center)[
    #text(size: 8pt, fill: luma(90))[#counter(page).display("1")]
  ],
)

#set text(
  font: ("Times New Roman", "SimSun"),
  fallback: true,
  size: 9pt,
  lang: "zh",
)
#set par(justify: true, leading: 0.55em, first-line-indent: 2em)
#set list(indent: 1.25em, body-indent: 0.45em, spacing: 0.25em)
#set enum(indent: 1.25em, body-indent: 0.45em, spacing: 0.25em)
#set heading(numbering: none)

#show heading.where(level: 1): it => block(above: 1.05em, below: 0.55em)[
  #set text(font: ("SimHei", "Arial"), size: 11pt, weight: "bold")
  #set par(first-line-indent: 0em)
  #it.body
]
#show heading.where(level: 2): it => block(above: 0.8em, below: 0.35em)[
  #set text(font: ("SimHei", "Arial"), size: 9.5pt, weight: "bold")
  #set par(first-line-indent: 0em)
  #it.body
]
#show figure.caption: set text(size: 7.5pt)
#show figure.caption: set par(justify: false, first-line-indent: 0em, leading: 0.35em)

#let journal-figure(path, caption, wide: false) = {
  let item = figure(
    image(path, width: 100%),
    caption: caption,
    supplement: none,
    numbering: none,
  )
  if wide {
    place(top + center, scope: "parent", float: true, clearance: 0.8em, item)
  } else {
    align(center, item)
  }
}

#let journal-table(caption: none, columns: 0, header: (), cells: (), wide: false) = {
  let item = figure(
    table(
      columns: (1fr,) * columns,
      align: (x, y) => if x == 0 { left } else { center },
      inset: (x: 2.4pt, y: 2pt),
      fill: (x, y) => if y == 0 { luma(235) } else { none },
      stroke: (x, y) => (
        top: if y == 0 { 0.8pt + luma(70) } else { none },
        bottom: if y == 0 { 0.55pt + luma(90) } else { 0.25pt + luma(190) },
      ),
      table.header(..header),
      ..cells,
    ),
    caption: caption,
    supplement: none,
    numbering: none,
  )
  if wide {
    place(top + center, scope: "parent", float: true, clearance: 0.8em, item)
  } else {
    align(center, item)
  }
}

#align(center)[
  #set par(first-line-indent: 0em, justify: false)
  #text(font: ("SimHei", "Arial"), size: 16pt, weight: "bold")[__TITLE__]

  #v(0.9em)
  #text(size: 10pt, weight: "bold")[【待补：作者姓名】]
  #linebreak()
  #text(size: 8.5pt)[【待补：作者单位、城市、邮编】]
  #linebreak()
  #text(size: 8pt)[通信作者：【待补】　E-mail：【待补】]
]

#v(0.7em)
#block(fill: luma(246), stroke: 0.35pt + luma(190), inset: 8pt, radius: 2pt)[
  #set par(first-line-indent: 2em, leading: 0.45em)
  #align(center)[#text(font: ("SimHei", "Arial"), weight: "bold", size: 9.5pt)[摘要]]
  __ZH_ABSTRACT__

  #set par(first-line-indent: 0em)
  *关键词：* __ZH_KEYWORDS__
]

#v(0.8em)
#align(center)[
  #set par(first-line-indent: 0em, justify: false)
  #text(size: 12pt, weight: "bold")[__EN_TITLE__]
  #linebreak()
  #text(size: 8.5pt)[【Authors and affiliations to be completed】]
]

#v(0.35em)
#block(inset: (x: 5pt, y: 3pt))[ 
  #set text(size: 8pt, lang: "en")
  #set par(first-line-indent: 0em, leading: 0.42em)
  *Abstract:* __EN_ABSTRACT__

  *Keywords:* __EN_KEYWORDS__
]

#v(0.45em)
#line(length: 100%, stroke: 0.5pt + luma(120))
#v(0.25em)

#columns(2, gutter: 7mm)[
  #paper-body(journal-table, journal-figure)
]
'''


def main() -> None:
    lines = SOURCE.read_text(encoding="utf-8").splitlines()
    title = lines[0].removeprefix("# ").strip()

    zh_section = _section(lines, "## 中文摘要", "## English title")
    keyword_idx = next(i for i, line in enumerate(zh_section) if line.startswith("**关键词：**"))
    zh_abstract = _paragraph_text(zh_section[:keyword_idx])
    zh_keywords = _paragraph_text(zh_section[keyword_idx:]).replace("**关键词：**", "", 1)

    en_title_section = _section(lines, "## English title", "## Abstract")
    en_title = _strip_markdown_emphasis(_paragraph_text(en_title_section))
    en_section = _section(lines, "## Abstract", "## 1 引言")
    en_keyword_idx = next(i for i, line in enumerate(en_section) if line.startswith("**Keywords:**"))
    en_abstract = _paragraph_text(en_section[:en_keyword_idx])
    en_keywords = _paragraph_text(en_section[en_keyword_idx:]).replace("**Keywords:**", "", 1)

    body_start = lines.index("## 1 引言")
    body_end = lines.index("## 附录 A 当前结果的复现索引")
    body_text = _convert_body(lines[body_start:body_end])

    entry_text = ENTRY_TEMPLATE
    entry_text = entry_text.replace("__TITLE__", _typst_inline(title))
    entry_text = entry_text.replace("__ZH_ABSTRACT__", _typst_inline(zh_abstract))
    entry_text = entry_text.replace("__ZH_KEYWORDS__", _typst_inline(zh_keywords))
    entry_text = entry_text.replace("__EN_TITLE__", _typst_inline(en_title))
    entry_text = entry_text.replace("__EN_ABSTRACT__", _typst_inline(en_abstract))
    entry_text = entry_text.replace("__EN_KEYWORDS__", _typst_inline(en_keywords))

    ENTRY.write_text(entry_text, encoding="utf-8", newline="\n")
    BODY.write_text(body_text, encoding="utf-8", newline="\n")
    print(f"wrote {ENTRY.relative_to(ROOT)}")
    print(f"wrote {BODY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
